### PR TITLE
Create regression.py

### PR DESCRIPTION
**Pull request by sakshi0461**
__1__

#1 

 

#### Short description of what this resolves:
Predict salary on the basis of work experience.

#### Changes proposed in this pull request and/or Screenshots of changes:
regression

-
-
-

### CODE REVIEW

**Comment by europe-asia-america** [comment]
Please edit your PR and provide the appropriate issue number. Add a description to this PR while you are at it.

**Comment by sakshi0461** [comment]
issue #1 fixed.

**Comment by europe-asia-america** [comment]
You mentioned #1 and not #2 although you completed both. Ideally your PR should fix one issue only and you open a second PR for fixing the next issue.

Truth is if I merge this you won't get any points since the bot that gives points will parse the first comment on this PR and find no `#1`. 

Please remove the task 1 question 2 file and make a new PR for that issue (so you have two PRs and get points for solving both issues.
Also, please follow the PR format so you get the points you have earned once I merge the PR. Add `#1` to the first comment in this thread.

**Comment by sakshi0461** [comment]
@Mrigyen removed task 1 question 2 file

**Pull request merged**
